In [1]:
#slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
slice2=arr[::2]
Reversed=arr[::-1]
print(slice1)
print(slice2)
print(Reversed)

[3 4 5 6]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


In [2]:
#slicing multi dimensional array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#slice rows 0 to 2 column 1 to 3
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [3]:
#extra act first column
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
col=arr[:,0]
print(col)


[1 4 7]


In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6


In [5]:
#basic indexing
arr=np.array([10,20,30,40,50])
print(arr[1])


20


In [6]:
#negative indexing
arr=np.array([10,20,30,40,50])
print(arr[-1])


50


In [7]:
#subset indexing
arr=np.array([10,20,30,40,50])
print(arr[1:4])


[20 30 40]


In [8]:
#specfic condition for indexing
arr=np.array([10,20,30,40,50])
print(arr[arr>25])


[30 40 50]


In [9]:
#horizontal join
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [10]:
#vertical join
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
#depth join
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)



[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [12]:
#spilt into 3 equal parts
arr1=np.array([1,2,3,4,5,6])
result=np.split(arr1,3)
print(result)



[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:

#spilt unequal parts
arr1=np.array([1,2,3,4,5])
result=np.array_split(arr1,3)
print(result)


[array([1, 2]), array([3, 4]), array([5])]
