In [18]:
import numpy as np
a=np.array([10,20,30,40,50])
print("one dimentional array:",a)


one dimentional array: [10 20 30 40 50]


In [19]:
import numpy as np
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("two dimentional array:",a)



two dimentional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [20]:
import numpy as np
z=np.zeros((3,5))
print("\n Array with all zeros:\n",z)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
import numpy as np
b=np.random.random((4,4))
print("\n array with random number:\n",b)


 array with random number:
 [[0.98626942 0.91195116 0.50879205 0.4027238 ]
 [0.34874639 0.93275783 0.35905127 0.05845142]
 [0.66973569 0.69768785 0.53549384 0.25608556]
 [0.81178547 0.54606338 0.19085999 0.71871577]]


In [24]:
import numpy as np
e=np.arange(0,10,1)
print("\n Range value:\n",e)


 Range value:
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape((4,3))
print("\n original array:\n",arr)
print("\n Reshaped array[4,3]:\n",newarr)

In [11]:
import numpy as np
z=np.zeros((5,3))
a=np.random.random((5,3))
s=np.arange(0,10,1)
arr=np.array([[7,8,6,8,8],[3,9,0,8,7],[1,2,3,1,2]])
newarr=arr.reshape((5,3))
print("\n Array with all zeros:\n",z)
print("\n Array with random number:\n",a)
print("\n Range Value:\n",s)
print("\n original array:\n",arr)
print("\n reshaped array[5,3]:\n",newarr)




 Array with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Array with random number:
 [[0.44138106 0.6414215  0.22336163]
 [0.10992391 0.04101447 0.39534494]
 [0.69709767 0.33198091 0.66722815]
 [0.90423531 0.41723442 0.51723535]
 [0.85898027 0.02430683 0.33980247]]

 Range Value:
 [0 1 2 3 4 5 6 7 8 9]

 original array:
 [[7 8 6 8 8]
 [3 9 0 8 7]
 [1 2 3 1 2]]

 reshaped array[5,3]:
 [[7 8 6]
 [8 8 3]
 [9 0 8]
 [7 1 2]
 [3 1 2]]


In [12]:
flat=arr.flatten()
print("Flattened array:\n",flat)

Flattened array:
 [7 8 6 8 8 3 9 0 8 7 1 2 3 1 2]


In [13]:
print("\n No of dimensions:",arr.ndim)



 No of dimensions: 2


In [14]:
print("\n shape of array:",arr.shape)


 shape of array: (3, 5)


In [15]:
print("\n Array element type:",arr.dtype)


 Array element type: int32


In [17]:
newtype=arr.astype('f')
print("\n Covert array element:\n",newtype)
print("coverted array:",newtype.dtype)


 Covert array element:
 [[7. 8. 6. 8. 8.]
 [3. 9. 0. 8. 7.]
 [1. 2. 3. 1. 2.]]
coverted array: float32


In [22]:
size=len(arr)
print("\n size of array:\n",arr.size)


 size of array:
 15
